using System.Collections.Generic;

namespace ASA_Save_Inspector.ObjectModel
{

    public partial class BondedDinoData
    {
        public string? dino_class { get; set; }
        public string? dino_name { get; set; }
        public int? id1 { get; set; }
        public int? id2 { get; set; }
    }

    public partial class FoliageGenerationInfo
    {
        public CustomList<object?>? properties { get; set; }
    }

    public partial class SaddleStructure
    {
        public string? bone_name { get; set; }
        public Vector? location { get; set; }
        public string? my_structure { get; set; }
        public Rotator? rotation { get; set; }
    }

    public partial class Dino
    {
        public double? ActorTransformX { get; set; }
        public double? ActorTransformY { get; set; }
        public double? ActorTransformZ { get; set; }
        public string? AddedStatPoints { get; set; }
        public double? AIRangeMultiplier { get; set; }
        public double? AlgaeQuantity { get; set; }
        public double? AlgaeSwimmingTimeOffset { get; set; }
        public bool? AllowWildBabyTaming { get; set; }
        public bool? AtePremiumFood { get; set; }
        public CustomList<TypeStringValue?>? AttachedCarts { get; set; }
        public CustomList<int?>? AttachedCartsIDs { get; set; }
        public double? BabyAge { get; set; }
        public TypeStringValue? BabyCuddleFood { get; set; }
        public NameStringValue? BabyCuddleType { get; set; }
        public Vector? BabyCuddleWalkStartingLocation { get; set; }
        public double? BabyNextCuddleTime { get; set; }
        public Properties? BackpackSaveData { get; set; }
        public NameStringValue? BackplateMode { get; set; }
        public bool? bAllowPublicSeating { get; set; }
        public int? BaseLevel { get; set; }
        public string? BaseStatPoints { get; set; }
        public bool? bAttemptTeleportToSurface { get; set; }
        public bool? bAutoChargeActive { get; set; }
        public bool? bBabyInitiallyUnclaimed { get; set; }
        public bool? bCanBeDamaged { get; set; }
        public bool? bChargeInfusedWebsModeOn { get; set; }
        public bool? bClimberRestoreToAttached { get; set; }
        public bool? bCollectVictimItems { get; set; }
        public bool? bCuddleRequestRefreshed { get; set; }
        public bool? bDinoHasBonded { get; set; }
        public bool? bDontWander { get; set; }
        public bool? bDroppedItemCollectionEnabled { get; set; }
        public bool? bEnableTamedMating { get; set; }
        public bool? bEnableTamedWandering { get; set; }
        public bool? bForceActivateAtMaxCharge { get; set; }
        public bool? bForceDisablingTaming { get; set; }
        public bool? bForcePreventExitingWater { get; set; }
        public bool? bHadStaticBase { get; set; }
        public bool? bIgnoreAllWhistles { get; set; }
        public bool? bIgnoreAllyLook { get; set; }
        public bool? bIgnoreNPCCountVolumes_0x0 { get; set; }
        public bool? bIncrementedZoneManagerDirectLink { get; set; }
        public bool? bIsAWildFollowerKnownServerside { get; set; }
        public bool? bIsBaby { get; set; }
        public bool? bIsBotIdle { get; set; }
        public bool? bIsCloneDino { get; set; }
        public bool? bIsCryopodded { get; set; }
        public bool? bIsDead { get; set; }
        public bool? bIsFemale { get; set; }
        public bool? bIsFlying { get; set; }
        public bool? bIsInRaftMode { get; set; }
        public bool? bIsInTurretMode { get; set; }
        public bool? bIsLatched { get; set; }
        public bool? bIsLazing { get; set; }
        public bool? bIsNaturallySleeping { get; set; }
        public bool? bIsNursing { get; set; }
        public bool? bIsParentWildDino { get; set; }
        public bool? bIsSleeping { get; set; }
        public bool? bIsSmallLion { get; set; }
        public bool? bIsUnderground { get; set; }
        public bool? bIsUsingCamo { get; set; }
        public double? BiteCorpseTime { get; set; }
        public bool? bNeutered { get; set; }
        public bool? bNurseVisualActive { get; set; }
        public CustomList<BondedDinoData?>? BondedDinoData { get; set; }
        public bool? bOnlyTargetConscious { get; set; }
        public bool? bPassiveFlee { get; set; }
        public bool? bPreventHibernation { get; set; }
        public bool? bRestoreToSeeking { get; set; }
        public bool? bSavedWhenStasised { get; set; }
        public bool? bServerInitializedDino { get; set; }
        public bool? bSlowfallEnabled { get; set; }
        public bool? bTamedAIAllowSpecialAttacks { get; set; }
        public bool? bTargetingIgnoredByWildDinos { get; set; }
        public bool? bTargetingIgnoreWildDinos { get; set; }
        public bool? bTimersAreInUTC { get; set; }
        public TypeStringValue? CharacterSavedDynamicBase { get; set; }
        public Vector? CharacterSavedDynamicBaseRelativeLocation { get; set; }
        public Quaternion? CharacterSavedDynamicBaseRelativeRotation { get; set; }
        public string? ClassName { get; set; }
        public Rotator? ClimberRestoreToClimbingRotation { get; set; }
        public int? CollectionSetting { get; set; }
        public string? ColorSetIndices { get; set; }
        public string? ColorSetNames { get; set; }
        public double? CorpseDestructionTime { get; set; }
        public double? CorpseDestructionTimer { get; set; }
        public double? CorruptSpawnInValue { get; set; }
        public string? CryopodUUID { get; set; }
        public CustomList<string?>? CrystalSockets { get; set; }
        public string? CurrentBackpackType { get; set; }
        public int? CurrentBotMode { get; set; }
        public NameStringValue? CurrentDefaultWhistleSkill { get; set; }
        public int? CurrentLevel { get; set; }
        public NameStringValue? CurrentMoralSupportState { get; set; }
        public TypeStringValue? CurrentNest { get; set; }
        public int? CurrentResinProjType { get; set; }
        public NameStringValue? CurrentShortDistanceSubBehavior { get; set; }
        public int? CurrentSpecificHarvestResourceIndex { get; set; }
        public double? CurrentTameAffinity { get; set; }
        public double? CurrentTrackDistance { get; set; }
        public int? currentWebWeaponAmmo { get; set; }
        public CustomList<double?>? DigestionPool { get; set; }
        public CustomList<DinoAncestor?>? DinoAncestors { get; set; }
        public CustomList<DinoAncestor?>? DinoAncestorsMale { get; set; }
        public double? DinoDownloadedAtTime { get; set; }
        public int? DinoID1 { get; set; }
        public int? DinoID2 { get; set; }
        public TypeStringValue? DirectLinkNPCZoneManager { get; set; }
        public Vector? DockingBayLocation { get; set; }
        public bool? DontDoMaterialSpawning { get; set; }
        public double? EmotionLevel { get; set; }
        public CustomList<string?>? EventTags { get; set; }
        public int? FireSourceIndex { get; set; }
        public FoliageGenerationInfo? FoliageGenerationInfo { get; set; }
        public CustomList<int?>? FoliageInventorySavedQuantities { get; set; }
        public int? FollowStoppingDistance { get; set; }
        public double? ForcedWildBabyAge { get; set; }
        public double? FriendModeEndTime { get; set; }
        public Properties? FriendStartTransform { get; set; }
        public double? FuelLevel { get; set; }
        public double? FuelPercent { get; set; }
        public CustomList<string?>? GeneTraits { get; set; }
        public int? GestationEggNumberOfLevelUpPointsApplied { get; set; }
        public int? GestationEggNumberOfMutationsApplied { get; set; }
        public int? GestationEggRandomMutationsFemale { get; set; }
        public int? GestationEggRandomMutationsMale { get; set; }
        public double? GestationEggTamedIneffectivenessModifier { get; set; }
        public TypeStringValue? HardLimitWildDinoToVolume { get; set; }
        public CustomList<int?>? HarvestResourceLevels { get; set; }
        public bool? HasSpawnedAHiveBefore { get; set; }
        public string? ImprinterName { get; set; }
        public string? ImprinterPlayerUniqueNetId { get; set; }
        public TypeStringValue? Instigator { get; set; }
        public string? InventoryUUID { get; set; }
        public bool? isBuried { get; set; }
        public bool? IsRolled { get; set; }
        public bool? isSeated { get; set; }
        public bool? IsUnderground { get; set; }
        public string? ItemArchetype { get; set; }
        public CustomList<TypeStringValue?>? LadderStructures { get; set; }
        public double? LastBeaverDamSpawn { get; set; }
        public double? LastEggSpawnChanceTime { get; set; }
        public double? LastEnterStasisTime { get; set; }
        public double? LastFeatherPluckTime { get; set; }
        public TypeIntValue? LastFriend { get; set; }
        public int? LastFriendTeam { get; set; }
        public double? LastInAllyRangeSerialized { get; set; }
        public TypeStringValue? LastLatchedISMC { get; set; }
        public int? LastLatchedISMCBodyIndex { get; set; }
        public double? LastMilkProductionTime { get; set; }
        public double? LastReincarnateTime { get; set; }
        public double? LastSkinnedTime { get; set; }
        public int? LastStackCount { get; set; }
        public double? LastStaminaUpdate { get; set; }
        public double? LastTameConsumedFoodTime { get; set; }
        public double? LastTimeFinishedTraining { get; set; }
        public double? LastTimeHarvested { get; set; }
        public double? LastTimeSheared { get; set; }
        public double? LastTimeSwimming_Algae { get; set; }
        public double? LastTimeUpdatedCharacterStatusComponent { get; set; }
        public double? LastTimeUpdatedCorpseDestructionTime { get; set; }
        public CustomList<double?>? LastTimeUsedSkillsArray { get; set; }
        public double? LastUnstasisStructureTime { get; set; }
        public double? LastUpdate { get; set; }
        public double? LastUpdatedBabyAgeAtTime { get; set; }
        public double? LastUpdatedGestationAtTime { get; set; }
        public double? LastUpdatedMatingAtTime { get; set; }
        public double? LastUpkeepNetworkTime { get; set; }
        public double? LastWildNestSpawnTime { get; set; }
        public Vector? LatchingDirection { get; set; }
        public Vector? LatchingSurfaceNormal { get; set; }
        public Properties? LatchTargetTransform { get; set; }
        public string? LatestUploadedFromServerName { get; set; }
        public int? LimitWildDinoToVolumenIndex { get; set; }
        public string? LimitWildDinoToVolumenTag { get; set; }
        public int? MoschLevelUpsAvailable { get; set; }
        public string? MutatedStatPoints { get; set; }
        public TypeStringValue? MyAIData { get; set; }
        public TypeStringValue? MyCharacterStatusComponent { get; set; }
        public TypeStringValue? MyDeathHarvestingComponent { get; set; }
        public TypeStringValue? MyDockingBay { get; set; }
        public TypeStringValue? MyTrack { get; set; }
        public double? NextAllowedMatingTime { get; set; }
        public double? NumOfFishHarvestedSoFarRare { get; set; }
        public double? NumOfFishHarvestedSoFarReg { get; set; }
        public int? NumTimesTrained { get; set; }
        public double? NursingTroughFoodEffectivenessMultiplier { get; set; }
        public int? OasisaurFoliagePresetIndex { get; set; }
        public double? OriginalCreationTime { get; set; }
        public string? OriginalNPCVolumeName { get; set; }
        public TypeStringValue? Owner { get; set; }
        public int? OwningPlayerID { get; set; }
        public string? OwningPlayerName { get; set; }
        public TypeStringValue? PaintingComponent { get; set; }
        public int? pickPocketingMode { get; set; }
        public string? PreviousUploadedFromServerName { get; set; }
        public int? ProductionMode { get; set; }
        public int? RandomMutationsFemale { get; set; }
        public int? RandomMutationsMale { get; set; }
        public double? RequiredTameAffinity { get; set; }
        public int? RequiredTamingFoodIndex { get; set; }
        public double? ReserveFuelPercent { get; set; }
        public double? ResourceAmount { get; set; }
        public CustomList<object?>? ResourceProduction { get; set; }
        public CustomList<SaddleStructure?>? SaddleStructures { get; set; }
        public CustomList<string?>? SavedDeathAnim { get; set; }
        public int? SaveDestroyWildDinosUnderVersion { get; set; }
        public double? SavedLastConsumeStoredXPCooldown { get; set; }
        public int? SavedLastValidTameVersion { get; set; }
        public string? ShortName { get; set; }
        public string? StatValues { get; set; }
        public double? StoredXP { get; set; }
        public TypeObjectValue? SubmarineStructure { get; set; }
        public bool? SupportsConsumablesAutoTransfer { get; set; }
        public int? TamedAggressionLevel { get; set; }
        public int? TamedAITargetingRange { get; set; }
        public double? TamedAtTime { get; set; }
        public TypeStringValue? TamedFollowTarget { get; set; }
        public string? TamedName { get; set; }
        public string? TamedOnServerName { get; set; }
        public string? TamedTimeStamp { get; set; }
        public double? TameIneffectivenessModifier { get; set; }
        public string? TamerString { get; set; }
        public double? TamingLastFoodConsumptionTime { get; set; }
        public int? TamingTeamID { get; set; }
        public int? TargetingTeam { get; set; }
        public Vector? TargetLatchingLoc { get; set; }
        public int? TherizinoLevelUpsAvailable { get; set; }
        public double? TimeOfLastFeeding { get; set; }
        public double? TimeOfLastHarvest { get; set; }
        public double? TotalCompanionModeNonPassiveXP { get; set; }
        public string? TribeName { get; set; }
        public bool? TrunkHasWater { get; set; }
        public int? UndergroundVisState { get; set; }
        public double? UnknownName_00000004 { get; set; }
        public int? UnknownName_0000003A { get; set; }
        public TypeIntValue? UnknownProperty { get; set; }
        public double? UntamedPoopTimeCache { get; set; }
        public string? UploadedFromServerName { get; set; }
        public string? UUID { get; set; }
        public double? WanderRadiusMultiplier { get; set; }
        public NameStringValue? WarningMode { get; set; }
        public double? WaterAmount { get; set; }
        public int? WildAggroResponseOffset { get; set; }
        public CustomList<TypeStringValue?>? WildFollowerRefs { get; set; }
        public TypeStringValue? WildFollowingParentRef { get; set; }
        public TypeStringValue? WildLimitTargetVolume { get; set; }
        public double? WildRandomScale { get; set; }
        public Properties? WildRidingStartTransform { get; set; }
    }

}
