namespace ASA_Save_Inspector.ObjectModel
{

    public partial class CustomFolderItem
    {
        public CustomList<ItemID?>? custom_folder_ids { get; set; }
        public int? inventory_comp_type { get; set; }
        public string? name { get; set; }
    }

    public partial class StoredTrait
    {
        public string? class_name { get; set; }
        public string? name { get; set; }
        public double? unique_id { get; set; }
    }

    public partial class Structure
    {
        public bool? Activated { get; set; }
        public double? ActivatedAtTime { get; set; }
        public double? ActorTransformX { get; set; }
        public double? ActorTransformY { get; set; }
        public double? ActorTransformZ { get; set; }
        public double? AimPitch { get; set; }
        public double? AimYaw { get; set; }
        public int? AISetting { get; set; }
        public bool? AllowPublicUse { get; set; }
        public int? AmmoCount { get; set; }
        public TypeStringValue? AssociatedStructure { get; set; }
        public int? AttachedDinoID1 { get; set; }
        public int? AttachedDinoID2 { get; set; }
        public CustomList<CustomItemData?>? AttachedDinos { get; set; }
        public int? AssociatedDinoID1 { get; set; }
        public int? AssociatedDinoID2 { get; set; }
        public CustomList<TypeStringValue?>? AttachedStructures { get; set; }
        public int? AttachedToDinoID1 { get; set; }
        public double? AttenuationPercent { get; set; }
        public int? AutoCloseTimeSetting { get; set; }
        public TypeStringValue? AutoCraftItemClass { get; set; }
        public int? AutoOpenSetting { get; set; }
        public bool? AutoRestInRangeEnabled { get; set; }
        public CustomList<Properties?>? AvailableLocationsBytes { get; set; }
        public bool? bAdminOnlyAccess { get; set; }
        public bool? bAllowEquppingItem { get; set; }
        public bool? bAllowPublicRetraction { get; set; }
        public bool? bAllowRemovalFromInventory { get; set; }
        public bool? bAutoActivateBoost { get; set; }
        public bool? bAutoCraftActivated { get; set; }
        public bool? bCanBeDamaged { get; set; }
        public bool? bCanSlot { get; set; }
        public bool? bConnectedToNonPipe { get; set; }
        public bool? bContainerActivated { get; set; }
        public bool? bDinoLinked { get; set; }
        public int? BedID { get; set; }
        public string? BedName { get; set; }
        public string? BedOwnerName { get; set; }
        public Properties? BeeData { get; set; }
        public bool? bEnableSorting { get; set; }
        public bool? bEquippedItem { get; set; }
        public bool? bForceIgnoreAllies { get; set; }
        public bool? bGeneratedCrateItems { get; set; }
        public bool? bHasAmmo { get; set; }
        public bool? bHasFruitItems { get; set; }
        public bool? bHasFuel { get; set; }
        public bool? bHasItems { get; set; }
        public bool? bHasPoop { get; set; }
        public bool? bHasResetDecayTime { get; set; }
        public bool? bHasRisen { get; set; }
        public bool? bHasWater { get; set; }
        public bool? bHideFromInventoryDisplay { get; set; }
        public bool? bHideFromRemoteInventoryDisplay { get; set; }
        public bool? bInitializedMe { get; set; }
        public bool? bInitializedRotation { get; set; }
        public bool? bIsBlueprint { get; set; }
        public bool? bisDonePlacing { get; set; }
        public bool? bIsClubArkReward { get; set; }
        public bool? bIsEngram { get; set; }
        public bool? bIsFertilized { get; set; }
        public bool? bIsFlipped { get; set; }
        public bool? bIsFlooded { get; set; }
        public bool? bIsFoundation { get; set; }
        public bool? bIsFrameHidden { get; set; }
        public bool? bIsHarvestingMode { get; set; }
        public bool? bIsInitialItem { get; set; }
        public bool? bIsLocked { get; set; }
        public bool? bIsPinLocked { get; set; }
        public bool? bIsPowered { get; set; }
        public bool? bIsRetracted { get; set; }
        public bool? bIsSecondaryAnchor { get; set; }
        public bool? bIsSeeded { get; set; }
        public bool? bIsSnapshotACapture { get; set; }
        public bool? bIsTargetListInclusion { get; set; }
        public bool? bIsUnderwater { get; set; }
        public bool? bIsWatered { get; set; }
        public int? BlacklistedItemCount { get; set; }
        public bool? bLastToggleActivated { get; set; }
        public int? BottleIndex { get; set; }
        public string? BoxName { get; set; }
        public bool? bPoweredHasBattery { get; set; }
        public bool? bPoweredUsingBattery { get; set; }
        public bool? bPreventUsingAsWirelessCraftingSource { get; set; }
        public bool? bSavedWhenStasised { get; set; }
        public bool? bSetInitialWater { get; set; }
        public bool? bSnapshotGender { get; set; }
        public bool? bStopped { get; set; }
        public bool? bUseDefaultSnapshotMaterial { get; set; }
        public bool? bUsingStructureColors { get; set; }
        public bool? bWasPlacementSnapped { get; set; }
        public int? ClockBoostState { get; set; }
        public bool? CollectCartConsumable { get; set; }
        public int? ConstructorPlayerDataID { get; set; }
        public int? ConstructorTargetingTeam { get; set; }
        public CustomList<TypeStringValue?>? CraftingItems { get; set; }
        public double? CropFruitFertilizerCache { get; set; }
        public double? CropPhaseFertilizerCache { get; set; }
        public double? CropRefreshInterval { get; set; }
        public double? CropRefreshTimeCache { get; set; }
        public int? CurrAttackTypeIndex { get; set; }
        public TypeStringValue? CurrentAmmoItemTemplate { get; set; }
        public double? currentChargeAmount { get; set; }
        public double? CurrentChargeAmount_Unreplicated { get; set; }
        public NameStringValue? CurrentCropPhase { get; set; }
        public double? CurrentDesiredBabyAge { get; set; }
        public int? CurrentEntryIndex { get; set; }
        public double? CurrentFoliageScale { get; set; }
        public double? CurrentFuelTimeCache { get; set; }
        public int? CurrentItemCount { get; set; }
        public int? CurrentOpenMode { get; set; }
        public int? CurrentPinCode { get; set; }
        public CustomList<int?>? CurrentPinCodes { get; set; }
        public double? CurrentRangeToVisualize { get; set; }
        public TypeStringValue? CurrentSnapshot { get; set; }
        public NameStringValue? CurrentState { get; set; }
        public string? CurrentVariantTag { get; set; }
        public CustomList<CustomFolderItem?>? CustomFolderItems { get; set; }
        public int? CustomCosmeticModSkinReplacementID { get; set; }
        public TypeStringValue? CustomCosmeticModSkinReplacementOriginalClass { get; set; }
        public int? CustomCosmeticModSkinVariantID { get; set; }
        public CustomList<CustomItemData?>? CustomItemDatas { get; set; }
        public TypeStringValue? DefaultDestinationTeleporter { get; set; }
        public Rotator? DefaultRotation { get; set; }
        public int? DefaultWithdrawIndex { get; set; }
        public int? DinoFeedingListType { get; set; }
        public int? DinoID1 { get; set; }
        public int? DinoID2 { get; set; }
        public CustomList<TypeStringValue?>? DinoTargetList { get; set; }
        public int? DisplayDefaultItemInventoryCount { get; set; }
        public int? DoorOpenState { get; set; }
        public double? EffectRadius { get; set; }
        public TypeStringValue? ElevatorBase { get; set; }
        public CustomList<TypeStringValue?>? EquippedItems { get; set; }
        public CustomList<LinearColor?>? FeatherColors { get; set; }
        public CustomList<TypeStringValue?>? FeedingDinoList { get; set; }
        public Vector? FinalLocation { get; set; }
        public bool? FinishedScanning { get; set; }
        public Vector? FirstCorner { get; set; }
        public CustomList<string?>? FoliageTypeSoftRef { get; set; }
        public TypeStringValue? FuelItemTrueClass { get; set; }
        public double? Health { get; set; }
        public bool? HideBase { get; set; }
        public bool? HidePedestal { get; set; }
        public bool? HideTopAndBottom { get; set; }
        public int? HotbarID { get; set; }
        public bool? IncludeHotbarOnDeposit { get; set; }
        public TypeStringValue? Instigator { get; set; }
        public CustomList<TypeStringValue?>? InventoryItems { get; set; }
        public string? InventoryUUID { get; set; }
        public Properties? InventoryWeapon { get; set; }
        public bool? IsMeshCropPlot { get; set; }
        public bool? IsPlacedInWindow { get; set; }
        public bool? IsPlacedOnRaft { get; set; }
        public bool? IsRangeHidden { get; set; }
        public bool? IsRoofHidden { get; set; }
        public bool? IsUndergroundTerminal { get; set; }
        public string? ItemArchetype { get; set; }
        public ItemID? ItemID { get; set; }
        public CustomList<ItemID?>? ItemIDs { get; set; }
        public int? ItemQuantity { get; set; }
        public CustomList<TypeStringValue?>? ItemSlots { get; set; }
        public int? ItemStatValues { get; set; }
        public int? ItemVersion { get; set; }
        public Vector? LandingPosition { get; set; }
        public double? LastActivatedTime { get; set; }
        public double? LastAppliedEffectTime { get; set; }
        public double? LastAttachedDinoTime { get; set; }
        public double? LastAutoDurabilityDecreaseTime { get; set; }
        public double? LastCheckedFuelTime { get; set; }
        public double? LastCropRefreshTime { get; set; }
        public double? LastDamagedAtTime { get; set; }
        public double? LastDeactivatedTime { get; set; }
        public double? LastEnterStasisTime { get; set; }
        public double? LastFireTime { get; set; }
        public double? LastHarvestedTime { get; set; }
        public double? LastInAllyRangeTimeSerialized { get; set; }
        public double? LastInventoryRefreshTime { get; set; }
        public double? LastLongReloadStartTime { get; set; }
        public int? LightIntensityLevel { get; set; }
        public TypeStringValue? LinkedAnchor { get; set; }
        public int? LinkedPlayerID { get; set; }
        public string? LinkedPlayerName { get; set; }
        public CustomList<string?>? LinkedStructureUUIDs { get; set; }
        public Properties? LocalOnlySkinCustomPersistentData { get; set; }
        public TypeStringValue? MainTerminal { get; set; }
        public double? MaxHealth { get; set; }
        public int? MaxItemCount { get; set; }
        public NameStringValue? Mode { get; set; }
        public bool? multiuseAnyoneCanAcquire { get; set; }
        public bool? multiuseOnlyAlliesCanAcquire { get; set; }
        public TypeStringValue? MyCropStructure { get; set; }
        public int? MyCustomCosmeticStructureSkinID { get; set; }
        public int? MyCustomCosmeticStructureSkinVariantID { get; set; }
        public TypeStringValue? MyStructureHarvestingComponent { get; set; }
        public TypeStringValue? MyTrain { get; set; }
        public double? NetDestructionTime { get; set; }
        public double? NetOrigCreationTime { get; set; }
        public double? NextAllowedUseTime { get; set; }
        public double? NextBoostActivationTime { get; set; }
        public double? NextBoostDeactivationTime { get; set; }
        public TypeStringValue? NextConsumeFuelGiveItemType { get; set; }
        public int? NumBullets { get; set; }
        public int? NumGreenHouseStructures { get; set; }
        public int? OpenState { get; set; }
        public double? OriginalCreationTime { get; set; }
        public string? OriginalPlacedTimeStamp { get; set; }
        public int? OriginalPlacerPlayerID { get; set; }
        public double? OriginalRespecStartTime { get; set; }
        public TypeStringValue? Owner { get; set; }
        public TypeStringValue? OwnerBot { get; set; }
        public TypeStringValue? OwnerBotClass { get; set; }
        public TypeStringValue? OwnerCropPlot { get; set; }
        public string? OwnerInventoryUUID { get; set; }
        public string? OwnerName { get; set; }
        public TypeStringValue? OwnerStructure { get; set; }
        public int? OwningPlayerID { get; set; }
        public string? OwningPlayerName { get; set; }
        public TypeStringValue? PaintingComponent { get; set; }
        public TypeStringValue? ParentStructure { get; set; }
        public double? PitctViewRotation { get; set; }
        public bool? Placed { get; set; }
        public TypeStringValue? PlacedOnFloorStructure { get; set; }
        public double? PlantBoundsZ { get; set; }
        public TypeStringValue? PlantedCrop { get; set; }
        public CustomList<int?>? PointsNeedTickUpdate { get; set; }
        public CustomList<TypeStringValue?>? PortholeLinks { get; set; }
        public CustomList<int?>? PortholeSaveState { get; set; }
        public CustomList<int?>? PortholeState { get; set; }
        public double? PreventCryopodDeploymentTilTime { get; set; }
        public TypeStringValue? PrimarySnappedStructureChild { get; set; }
        public TypeStringValue? PrimarySnappedStructureParent { get; set; }
        public int? RadiusSetting { get; set; }
        public int? RangeSetting { get; set; }
        public int? RemainingAvailableCellQuantity { get; set; }
        public int? Repeat { get; set; }
        public CustomList<Properties?>? ReplicatedDinoInfo { get; set; }
        public TypeStringValue? ReplicatedFuelItemClass { get; set; }
        public CustomList<Properties?>? ReplicatedNetInfos { get; set; }
        public int? ReplicatedShards { get; set; }
        public TypeStringValue? ReplicatedStructureMySkinClass { get; set; }
        public int? ResourceCount { get; set; }
        public TypeStringValue? SaddleDino { get; set; }
        public double? SavedDurability { get; set; }
        public int? SavedForceDefaultInventoryRefreshVersion { get; set; }
        public int? SavedItemVersion { get; set; }
        public TypeStringValue? SelectedResourceClass { get; set; }
        public int? SelectedRotationIndex { get; set; }
        public CustomList<int?>? SelectedRotationIndexes { get; set; }
        public TypeStringValue? SelectedStructureTypeToAffect { get; set; }
        public TypeStringValue? ServerHotbar { get; set; }
        public int? Shuffle { get; set; }
        public string? SignText { get; set; }
        public double? SignTextScale { get; set; }
        public Properties? SkinPersistentData { get; set; }
        public int? SlotIndex { get; set; }
        public string? SnapOverrideTag { get; set; }
        public int? SnapshotPoseIndex { get; set; }
        public CustomList<int?>? SortingInputAmounts { get; set; }
        public CustomList<TypeStringValue?>? SortingInputs { get; set; }
        public TypeStringValue? SpawnedForDino { get; set; }
        public int? SpawnedForDinoID1 { get; set; }
        public int? SpawnedForDinoID2 { get; set; }
        public Vector? StartLocation { get; set; }
        public int? StayOpenSetting { get; set; }
        public Properties? StoredCreatureData { get; set; }
        public CustomList<StoredTrait?>? StoredTraits { get; set; }
        public int? StructureColors { get; set; }
        public int? StructureID { get; set; }
        public TypeStringValue? StructureSkinClass { get; set; }
        public CustomList<TypeStringValue?>? StructuresPlacedOnFloor { get; set; }
        public int? TargetingTeam { get; set; }
        public double? TempControlValue { get; set; }
        public int? TempSlotIndex { get; set; }
        public CustomList<TypeStringValue?>? TetheredDinos { get; set; }
        public int? TilledCurrentCount { get; set; }
        public CustomList<double?>? TimesItemsAdded { get; set; }
        public double? timeStateStarted { get; set; }
        public double? TopAndBottomRotation { get; set; }
        public int? TotalAvailableCellQuantity { get; set; }
        public Properties? TrackData_FirstPoint { get; set; }
        public bool? TrackData_FromIncline { get; set; }
        public bool? TrackData_IsFlipped { get; set; }
        public bool? TrackData_ToIncline { get; set; }
        public int? TribeGroupInventoryRank { get; set; }
        public int? TribeGroupStructureRank { get; set; }
        public CustomList<Properties?>? UnavailableLocationsBytes { get; set; }
        public string? UUID { get; set; }
        public double? VolumePercent { get; set; }
        public int? WarningSetting { get; set; }
        public bool? WasInitiallyPlaced { get; set; }
        public double? WaterAmount { get; set; }
        public Properties? WirelessExchangeRefs { get; set; }
        public CustomList<int?>? WithdrawAmounts { get; set; }
        public double? YawViewRotation { get; set; }
    }

}
