using System;
using System.Collections.Generic;

namespace ASA_Save_Inspector
{
    public static class DinoNames
    {
        public static Dictionary<string, string> Names = new Dictionary<string, string>()
        {
            { "ZombieWyvern_Character_BP_Poison", "Zombie Poison Wyvern" },
            { "ZombieWyvern_Character_BP_Lightning", "Zombie Lightning Wyvern" },
            { "ZombieWyvern_Character_BP_Fire", "Zombie Fire Wyvern" },
            { "ZombieDodo_Character_BP", "Zomdodo" },
            { "Zombie_Character_BP_Skinny", "Skinny Revenant" },
            { "Zombie_Character_BP_Hulking", "Hulking Revenant" },
            { "Zombie_Character_BP_Bloated", "Bloated Revenant" },
            { "Zeppelin_Character_BP", "Zeppelin" },
            { "Yutyrannus_Character_BP", "Yutyrannus" },
            { "YoungIceFox_DinoCompanion_Character_WildClone_BP", "Veilwyn (Clone)" },
            { "YoungIceFox_DinoCompanion_Character_BP", "Veilwyn" },
            { "YoungIceFox_Character_BP_Corrupted_Zombie", "Veilwyn (Revenant)" },
            { "YiLing_Character_BP", "Yi Ling" },
            { "Yeti_Character_BP_Santa", "Santa's Big Helper" },
            { "Yeti_Character_BP_Abominable", "Abominable Snowman" },
            { "Yeti_Character_BP", "Yeti" },
            { "Xiphactinus_Character_BP_ASA", "Xiphactinus" },
            { "Xenomorph_Character_BP_Male_Tamed_Gen2", "R-Reaper King" },
            { "Xenomorph_Character_BP_Male_Tamed_Corrupt", "Corrupted Reaper King" },
            { "Xenomorph_Character_BP_Male_Tamed", "Reaper King" },
            { "Xenomorph_Character_BP_Male_Surface", "Reaper King (Surface)" },
            { "Xenomorph_Character_BP_Male_Minion", "Reaper King" },
            { "Xenomorph_Character_BP_Male_Lunar", "X-Reaper King" },
            { "Xenomorph_Character_BP_Male_Gen2", "R-Reaper King" },
            { "Xenomorph_Character_BP_Male_Chupa", "Reaper King" },
            { "Xenomorph_Character_BP_Male", "Reaper King" },
            { "Xenomorph_Character_BP_Female_Gen2", "R-Reaper Queen" },
            { "Xenomorph_Character_BP_Female", "Reaper Queen" },
            { "Xenomorph_Character_BP_ASA", "Reaper" },
            { "Wyvern_Character_BP_ZombiePoison", "Zombie Poison Wyvern" },
            { "Wyvern_Character_BP_ZombieLightning", "Zombie Lightning Wyvern" },
            { "Wyvern_Character_BP_ZombieFire", "Zombie Fire Wyvern" },
            { "Wyvern_Character_BP_Water", "Water Wyvern" },
            { "Wyvern_Character_BP_Poison", "Poison Wyvern" },
            { "Wyvern_Character_BP_Lightning", "Lightning Wyvern" },
            { "Wyvern_Character_BP_Ice", "Ice Wyvern" },
            { "Wyvern_Character_BP_Fire_Corrupt", "Corrupted Wyvern" },
            { "Wyvern_Character_BP_Fire", "Fire Wyvern" },
            { "Wyvern_Character_BP_Base", "Wyvern" },
            { "Vulture_Character_BP", "Vulture" },
            { "Vulcanite_Character_BP", "Vulcanite" },
            { "VRMainBoss_Character", "Corrupted Master Controller" },
            { "Volcano_Trike_Character_BP", "X-Triceratops" },
            { "Volcano_Rex_Character_BP", "X-Rex" },
            { "Volcano_Golem_Character_BP", "X-Rock Elemental" },
            { "Volcano_Ankylo_Character_BP", "X-Ankylosaurus" },
            { "Volcano_Allo_Character_BP", "X-Allosaurus" },
            { "ValMegaraptor_Character_BP_Boss_Medium", "Megaraptor (Beta)" },
            { "ValMegaraptor_Character_BP_Boss_Hard", "Megaraptor (Alpha)" },
            { "ValMegaraptor_Character_BP_Boss_Easy", "Megaraptor (Gamma)" },
            { "ValMegaraptor_Character_BP", "Megaraptor" },
            { "Tusoteuthis_Character_BP", "Tusoteuthis" },
            { "Turtle_Character_BP_Rockwell", "R-Carbonemys" },
            { "Turtle_Character_BP_Aberrant", "Aberrant Carbonemys" },
            { "Turtle_Character_BP", "Carbonemys" },
            { "Turkey_Character_BP_Event", "Murder Turkey" },
            { "Turkey_Character_BP", "Turkey" },
            { "Tropeognathus_Character_BP", "Tropeognathus" },
            { "Troodon_Character_BP_Corrupted_Zombie", "Troodon (Revenant)" },
            { "Troodon_Character_BP", "Troodon" },
            { "Trilobite_Character_Aberrant", "Aberrant Trilobite" },
            { "Trilobite_Character", "Trilobite" },
            { "Trike_Character_BP_Lightning", "Triceratops (Lightning)" },
            { "Trike_Character_BP_Corrupt", "Corrupted Triceratops" },
            { "Trike_Character_BP_Aberrant", "Aberrant Triceratops" },
            { "Trike_Character_BP", "Triceratops" },
            { "Tridacna_Character_BP", "Tridacna" },
            { "Train_Character", "Train Engine" },
            { "Toad_Character_BP_Aberrant", "Aberrant Beelzebufo" },
            { "Toad_Character_BP", "Beelzebufo" },
            { "Titanosaur_Character_BP", "Titanosaur" },
            { "Tireme_BP_Child", "Tireme" },
            { "Tiktaalik_Character_BP", "Tiktaalik" },
            { "Thylacoleo_Character_BP_Thrall", "Thylacoleo (Thrall)" },
            { "Thylacoleo_Character_BP_Eden", "R-Thylacoleo" },
            { "Thylacoleo_Character_BP", "Thylacoleo" },
            { "Thunnus_Character_BP", "Thunnus" },
            { "Thrall_Character_BP_WithSniperRifle", "Thrall with sniper rifle" },
            { "Thrall_Character_BP_WithShotgun", "Thrall with shotgun" },
            { "Thrall_Character_BP_WithRocketLauncher", "Thrall with rocket launcher" },
            { "Thrall_Character_BP_WithFlamethrower", "Thrall with flamethrower" },
            { "Thrall_Character_BP_WithCrossbow", "Thrall with crossbow" },
            { "Thrall_Character_BP_WithBola", "Thrall with bola" },
            { "Thrall_Character_BP_Tamer", "Thrall Tamer" },
            { "Thrall_Character_BP_SoldierWithPistol", "Thrall Soldier (with pistol)" },
            { "Thrall_Character_BP_Soldier", "Thrall Soldier" },
            { "Thrall_Character_BP_Fighter", "Thrall Fighter" },
            { "Thrall_Character_BP_Cultist", "Thrall Cultist" },
            { "Therizino_Character_BP_Thrall", "Therizinosaur (Thrall)" },
            { "Therizino_Character_BP_Corrupted_Zombie", "Therizinosaur (Revenant)" },
            { "Therizino_Character_BP", "Therizinosaur" },
            { "TerrorBird_Character_BP", "Terror Bird" },
            { "TekWyvern_Character_BP", "Voidwyrm" },
            { "TekStrider_Character_BP", "Tek Stryder" },
            { "TekHoverSkiff_Character_BP", "Tek Skiff" },
            { "Tapejara_Character_BP", "Tapejara" },
            { "Takifugu_Character_BP", "Takifugu" },
            { "Summoner_Character_BP", "Summoner" },
            { "Stereolepis_Character_BP", "Stereolepis" },
            { "Stego_Character_BP_Lightning", "Stegosaurus (Lightning)" },
            { "Stego_Character_BP_Corrupted_Zombie", "Stegosaurus (Revenant)" },
            { "Stego_Character_BP_Corrupt", "Corrupted Stegosaurus" },
            { "Stego_Character_BP_Aberrant", "Aberrant Stegosaurus" },
            { "Stego_Character_BP", "Stegosaurus" },
            { "Stag_Character_BP", "Megaloceros" },
            { "SpiritBear_Character_BP", "Elderclaw" },
            { "Spino_Character_BP_Thrall", "Spinosaurus (Thrall)" },
            { "Spino_Character_BP_Lightning", "Spinosaurus (Lightning)" },
            { "Spino_Character_BP_Corrupted_Zombie", "Spinosaurus (Revenant)" },
            { "Spino_Character_BP_Corrupt", "Corrupted Spinosaur" },
            { "Spino_Character_BP_Aberrant", "Aberrant Spinosaur" },
            { "Spino_Character_BP", "Spinosaur" },
            { "SpineyLizard_Character_BP", "Thorny Dragon" },
            { "Spindles_Character_BP_Rockwell", "R-Velonasaur" },
            { "Spindles_Character_BP", "Velonasaur" },
            { "SpiderS_Character_BP_Juvenile", "Araneo (Juvenile)" },
            { "SpiderS_Character_BP_Aberrant", "Aberrant Araneo" },
            { "SpiderS_Character_BP", "Araneo" },
            { "SpiderL_VAL_Character_BP", "Broodmother (Valguero)" },
            { "SpiderL_Character_BP_TheCenterMedium", "Broodmother (Beta)" },
            { "SpiderL_Character_BP_TheCenterHard", "Broodmother (Alpha)" },
            { "SpiderL_Character_BP_TheCenterEasy", "Broodmother (Gamma)" },
            { "SpiderL_Character_BP_Medium", "Broodmother (Beta)" },
            { "SpiderL_Character_BP_Hard", "Broodmother (Alpha)" },
            { "SpiderL_Character_BP_Easy", "Broodmother (Gamma)" },
            { "SpiderL_Character_BP", "Broodmother" },
            { "SpaceWhale_Character_BP", "Astrocetus" },
            { "SpaceDolphin_Character_BP", "Astrodelphis" },
            { "SnowMonster_Character_BP_Thrall", "Ossidon (Thrall)" },
            { "SnowMonster_Character_BP_Corrupt_Zombie", "Ossidon (Revenant)" },
            { "SnowMonster_Character_BP", "Ossidon" },
            { "SnowDragon_Character_BP", "Aureliax" },
            { "Snow_Yutyrannus_Character_BP", "X-Yutyrannus" },
            { "Snow_Saber_Character_BP", "X-Sabertooth" },
            { "Snow_Rhino_Character_BP", "X-Rhino" },
            { "Snow_Otter_Character_BP", "X-Otter" },
            { "Snow_Argent_Character_BP", "X-Argentavis" },
            { "Sinomacrops_Character_BP", "Sinomacrops" },
            { "ShoulderDragon_Character_BP_Winter", "Drakeling (Winter)" },
            { "ShoulderDragon_Character_BP_Summer", "Drakeling (Summer)" },
            { "ShoulderDragon_Character_BP_Spring", "Drakeling (Spring)" },
            { "ShoulderDragon_Character_BP_Autumn", "Drakeling (Autumn)" },
            { "ShoulderDragon_Character_BP", "Drakeling" },
            { "Sheep_Character_BP_Aberrant", "Aberrant Ovis" },
            { "Sheep_Character_BP", "Ovis" },
            { "Shastasaurus_Character_BP", "Shastasaurus" },
            { "Shapeshifter_Small_Character_BP", "Ferox (Small)" },
            { "Shapeshifter_Large_Character_BP", "Ferox (Large)" },
            { "Seahorse_Character_BP", "Seahorse" },
            { "Scout_Character_BP", "Scout" },
            { "Scorpion_Character_BP_Thrall", "Pulmonoscorpius (Thrall)" },
            { "Scorpion_Character_BP_Aberrant", "Aberrant Pulmonoscorpius" },
            { "Scorpion_Character_BP", "Pulmonoscorpius" },
            { "Sauropod_Character_BP_Rockwell", "R-Brontosaurus" },
            { "Sauropod_Character_BP_Corrupt_Zombie", "Brontosaurus (Revenant)" },
            { "Sauropod_Character_BP", "Brontosaurus" },
            { "Sarco_Character_BP_Aberrant", "Aberrant Sarco" },
            { "Sarco_Character_BP", "Sarco" },
            { "Salmon_Character_BP", "Sabertooth Salmon" },
            { "Salmon_Character_Aberrant", "Aberrant Salmon" },
            { "Saber_Character_BP_Thrall", "Sabertooth (Thrall)" },
            { "Saber_Character_BP_Corrupted_Zombie", "Sabertooth (Revenant)" },
            { "Saber_Character_BP", "Sabertooth" },
            { "RubbleGolem_Character_BP", "Rubble Golem" },
            { "RockwellNode_Character_BP_FinalFight", "Rockwell Prime" },
            { "Rockwell_Character_BP", "Rockwell" },
            { "RockGolem_Character_BP", "Rock Elemental" },
            { "RockDrake_Character_BP_Corrupt", "Corrupted Rock Drake" },
            { "RockDrake_Character_BP", "Rock Drake" },
            { "RiftCrawler_Character_BP", "Riftcrawler" },
            { "Rhynio_Character_BP", "Rhyniognatha" },
            { "Rhino_Character_BP", "Woolly Rhino" },
            { "Rex_Character_BP_Thrall", "Rex (Thrall)" },
            { "Rex_Character_BP_Lightning", "Rex (Lightning)" },
            { "Rex_Character_BP_Corrupt_Zombie", "Rex (Revenant)" },
            { "Rex_Character_BP_Corrupt", "Corrupted Rex" },
            { "Rex_Character_BP", "Rex" },
            { "Reindeer_Character_BP_Minigame", "Reindeer" },
            { "Rare_Lunar_Salmon_Character_BP", "X-Salmon (Rare)" },
            { "Raptor_Character_BP_Thrall", "Raptor (Thrall)" },
            { "Raptor_Character_BP_Lightning", "Raptor (Lightning)" },
            { "Raptor_Character_BP_Corrupted_Zombie", "Raptor (Revenant)" },
            { "Raptor_Character_BP_Corrupt", "Corrupted Raptor" },
            { "Raptor_Character_BP_Aberrant", "Aberrant Raptor" },
            { "Raptor_Character_BP", "Raptor" },
            { "Ragnarok_Wyvern_Override_Ice", "Ice Wyvern" },
            { "Raft_BP", "Raft" },
            { "Quetz_Character_BP_Rockwell", "R-Quetzal" },
            { "Quetz_Character_BP", "Quetzal" },
            { "Qarmoutus_Character_BP", "Qarmoutus" },
            { "Pygocentrus_Character_BP", "Pygocentrus" },
            { "Purlovia_Character_BP_Polar", "Purlovia (Polar)" },
            { "Purlovia_Character_BP_Aberrant", "Aberrant Purlovia" },
            { "Purlovia_Character_BP", "Purlovia" },
            { "Pteroteuthis_Char_BP_Surface", "Seeker (Surface)" },
            { "Pteroteuthis_Char_BP", "Seeker" },
            { "Ptero_Character_BP_Lightning", "Pteranodon (Lightning)" },
            { "Ptero_Character_BP_Corrupted_Zombie", "Pteranodon (Revenant)" },
            { "Ptero_Character_BP_Corrupt", "Corrupted Pteranodon" },
            { "Ptero_Character_BP", "Pteranodon" },
            { "Procoptodon_Character_BP_Eden", "R-Procoptodon" },
            { "Procoptodon_Character_BP", "Procoptodon" },
            { "Polar_Bear", "Polar Bear" },
            { "Plesiosaur_Character_BP", "Plesiosaur" },
            { "PlayerPawnTest", "Human" },
            { "Piranha_Character_BP_Aberrant", "Aberrant Piranha" },
            { "Piranha_Character_BP", "Piranha" },
            { "Phoenix_Character_BP", "Phoenix" },
            { "Phiomia_Character_BP", "Phiomia" },
            { "Pela_Character_BP", "Pelagornis" },
            { "Pegomastax_Character_BP_Grouch", "Pegomastax Grouch" },
            { "Pegomastax_Character_BP", "Pegomastax" },
            { "Paracer_Character_BP_Lightning", "Paraceratherium (Lightning)" },
            { "Paracer_Character_BP_Corrupt", "Corrupted Paraceratherium" },
            { "Paracer_Character_BP_Aberrant", "Aberrant Paraceratherium" },
            { "Paracer_Character_BP", "Paraceratherium" },
            { "Para_Character_BP_Eden", "R-Parasaur" },
            { "Para_Character_BP_Corrupted_Zombie", "Parasaur (Revenant)" },
            { "Para_Character_BP_Aberrant", "Aberrant Parasaur" },
            { "Para_Character_BP", "Parasaur" },
            { "Pachyrhino_Character_BP", "Pachyrhinosaurus" },
            { "Pachy_Character_BP", "Pachy" },
            { "Owl_Character_BP_Eden", "R-Snow Owl" },
            { "Owl_Character_BP", "Snow Owl" },
            { "Oviraptor_Character_BP_Aberrant", "Aberrant Oviraptor" },
            { "Oviraptor_Character_BP", "Oviraptor" },
            { "Otter_Character_BP_Aberrant", "Aberrant Otter" },
            { "Otter_Character_BP", "Otter" },
            { "Ossidon", "Ossidon" },
            { "Onchopristis_Character_BP", "Onchopristis" },
            { "Ocepechelon_Character_BP", "Ocepechelon" },
            { "Ocean_Mosa_Character_BP", "X-Mosasaur" },
            { "Ocean_Megalodon_Character_BP", "X-Megalodon" },
            { "Ocean_Dunkle_Character_BP", "X-Dunkleosteus" },
            { "Ocean_Dolphin_Character_BP", "X-Ichthyosaurus" },
            { "Ocean_Basilosaurus_Character_BP", "X-Basilosaurus" },
            { "Oasisaur_Character_BP", "Oasisaur" },
            { "NamelessCreature_Character_BP", "Nameless (Svartalfheim)" },
            { "Mudpuppy_Character_BP", "Mudpuppy" },
            { "MotorRaft_BP", "Motorboat" },
            { "Moth_Character_BP", "Lymantria" },
            { "Moschops_Character_BP_Aberrant", "Aberrant Moschops" },
            { "Moschops_Character_BP", "Moschops" },
            { "Mosa_Character_BP_Mega_Cave", "Alpha Mosasaur (Cave)" },
            { "Mosa_Character_BP_Mega", "Alpha Mosasaur" },
            { "Mosa_Character_BP_Cave", "Mosasaurus (Cave)" },
            { "Mosa_Character_BP", "Mosasaurus" },
            { "Monodon_Character_BP", "Monodon" },
            { "Monkey_Character_BP_Aggressive_Med", "Mesopithecus (Boss Minion)" },
            { "Monkey_Character_BP", "Mesopithecus" },
            { "MoleRat_Character_BP", "Roll Rat" },
            { "Minotaur_Character_BP", "Minotaur" },
            { "MilkGlider_Character_BP", "Maewing" },
            { "Microraptor_Character_BP", "Microraptor" },
            { "MicrobeSwarmChar_BP", "Parakeet Fish School" },
            { "Mek_Character_BP", "Mek" },
            { "MegaZombie_Character_BP_Hulking", "Alpha Hulking Revenant" },
            { "MegaXenomorph_Character_BP_Male_Surface", "Alpha Reaper King (Surface)" },
            { "MegaWyvern_Character_BP_Fire", "Alpha Fire Wyvern" },
            { "Megatherium_Character_BP_Thrall", "Megatherium (Thrall)" },
            { "Megatherium_Character_BP_Eden", "R-Megatherium" },
            { "Megatherium_Character_BP", "Megatherium" },
            { "MegaSnowMonster_Character_BP", "Alpha Ossidon" },
            { "MegaRex_Character_BP_Corrupt", "Alpha Corrupted Rex" },
            { "MegaRex_Character_BP", "Alpha Rex" },
            { "MegaRaptor_Character_BP", "Alpha Raptor" },
            { "MegaMek_Character_BP", "Mega Mek" },
            { "MegaMegalodon_Character_BP", "Alpha Megalodon" },
            { "Megalosaurus_Character_BP_TekCave", "Megalosaurus (Tek Cave)" },
            { "Megalosaurus_Character_BP_Aberrant", "Aberrant Megalosaurus" },
            { "Megalosaurus_Character_BP", "Megalosaurus" },
            { "Megalodon_Character_BP", "Megalodon" },
            { "Megalania_Character_BP_Aberrant", "Aberrant Megalania" },
            { "Megalania_Character_BP", "Megalania" },
            { "MegaDeathworm_Character_BP", "Alpha Deathworm" },
            { "MegaCrab_Character_BP", "Alpha Karkinos" },
            { "MegaCarno_Character_BP", "Alpha Carnotaurus" },
            { "MegaBasilisk_Character_BP", "Alpha Basilisk" },
            { "Mega_Tusoteuthis_Character_BP", "Alpha Tusoteuthis" },
            { "MantisShrimp_Character_BP", "Mantis Shrimp" },
            { "Mantis_Character_BP", "Mantis" },
            { "Manticore_Character_BP_Medium_Ragnarok", "Manticore (Beta)" },
            { "Manticore_Character_BP_Medium", "Manticore (Beta)" },
            { "Manticore_Character_BP_Hard_Ragnarok", "Manticore (Alpha)" },
            { "Manticore_Character_BP_Hard", "Manticore (Alpha)" },
            { "Manticore_Character_BP_Easy_Ragnarok", "Manticore (Gamma)" },
            { "Manticore_Character_BP_Easy", "Manticore (Gamma)" },
            { "Manticore_Character_BP", "Manticore" },
            { "Manta_Character_BP_Aberrant", "Aberrant Manta" },
            { "Manta_Character_BP", "Manta" },
            { "Mammoth_Character_BP_Corrupted_Zombie", "Mammoth (Revenant)" },
            { "Mammoth_Character_BP", "Mammoth" },
            { "Malleocephalus_Character_BP", "Malleocephalus" },
            { "Maelizard_Character_BP", "Maeguana" },
            { "Macrophage_Swarm_Character", "Macrophage" },
            { "Lystro_Character_BP_Aberrant", "Aberrant Lystrosaurus" },
            { "Lystro_Character_BP", "Lystrosaurus" },
            { "Lunar_Salmon_Character_BP", "X-Salmon" },
            { "LostCharge_LanternPet_Char_BP", "Gloon" },
            { "Liopleurodon_Character_BP", "Liopleurodon" },
            { "LionfishLion_Character_BP", "Shadowmane" },
            { "Lightbug_Character_BaseBP", "Glowbug" },
            { "Leedsichthys_Character_BP", "Leedsichthys" },
            { "Leech_Character_Diseased", "Diseased Leech" },
            { "Leech_Character", "Leech" },
            { "LavaGolem_Character_BP", "Lava Golem" },
            { "LanternPug_Character_BP", "Bulbdog" },
            { "LanternLizard_Character_BP", "Glowtail" },
            { "LanternGoat_Character_BP", "Shinehorn" },
            { "LanternBird_Character_BP", "Featherlight" },
            { "Lamprey_Character", "Lamprey" },
            { "Kirayli_Character_BP", "Kirayli" },
            { "KingKaiju_Character_BP_Gamma", "King Titan (Gamma)" },
            { "KingKaiju_Character_BP_Beta", "King Titan (Beta)" },
            { "KingKaiju_Character_BP_Alpha", "King Titan (Alpha)" },
            { "KingKaiju_Character_BP", "King Titan" },
            { "Kentro_Character_BP", "Kentrosaurus" },
            { "Kathreptis_Character_BP", "Kathreptis" },
            { "Kaprosuchus_Character_BP", "Kaprosuchus" },
            { "Kairuku_Character_BP", "Kairuku" },
            { "JumpingSpider_Character_BP", "Cosmo" },
            { "Jugbug_Water_Character_BP", "Water Jugbug" },
            { "Jugbug_Oil_Character_BP", "Oil Jugbug" },
            { "Jugbug_Character_BaseBP", "Jug Bug" },
            { "JerboaElfSleigh_Character_BP", "Jerboa (Elf Sleigh)" },
            { "JerboaElf_Character_BP", "Jerboa (Elf)" },
            { "Jerboa_Character_BP", "Jerboa" },
            { "Istiophorus_Character_BP", "Istiophorus" },
            { "InsectSwarmChar_BP", "Insect Swarm" },
            { "Iguanodon_Character_BP_Corrupted_Zombie", "Iguanodon (Revenant)" },
            { "Iguanodon_Character_BP_Aberrant", "Aberrant Iguanodon" },
            { "Iguanodon_Character_BP", "Iguanodon" },
            { "Ichthyornis_Character_BP", "Ichthyornis" },
            { "Iceworm_Queen_Character_BP", "Iceworm Queen" },
            { "Iceworm_Character_Minion_BP_smaller", "Iceworm" },
            { "IceKaiju_Character_BP_Medium", "Ice Titan (Beta)" },
            { "IceKaiju_Character_BP_Hard", "Ice Titan (Alpha)" },
            { "IceKaiju_Character_BP_Easy", "Ice Titan (Gamma)" },
            { "IceKaiju_Character_BP", "Ice Titan" },
            { "IceJumper_Character_BP", "Managarmr" },
            { "IceGolem_Character_BP", "Ice Golem" },
            { "Hyaenodon_Character_BP", "Hyaenodon" },
            { "HoneyBee_Character_BP", "Honey Bee" },
            { "Homarus_Character_BP", "Homarus" },
            { "Hesperornis_Character_BP", "Hesperornis" },
            { "HelperBot_Character_BP", "SIR-5RM8" },
            { "HelperBot_Character_B", "Sir-5rM8" },
            { "Helicoprion_Character_BP", "Helicoprion" },
            { "Griffin_Character_Minion_BP", "Griffin" },
            { "Griffin_Character_BP", "Griffin" },
            { "Gorilla_Character_BP_TheCenter_Medium", "Megapithecus (Beta)" },
            { "Gorilla_Character_BP_TheCenter_Hard", "Megapithecus (Alpha)" },
            { "Gorilla_Character_BP_TheCenter_Easy", "Megapithecus (Gamma)" },
            { "Gorilla_Character_BP_Medium", "Megapithecus (Beta)" },
            { "Gorilla_Character_BP_Hard", "Megapithecus (Alpha)" },
            { "Gorilla_Character_BP_Easy", "Megapithecus (Gamma)" },
            { "Gorilla_Character_BP", "Megapithecus" },
            { "Gigantoraptor_Character_BP_Aberrant", "Aberrant Gigantoraptor" },
            { "Gigantoraptor_Character_BP", "Gigantoraptor" },
            { "Gigant_Character_BP_TekCave", "Giganotosaurus (Tek Cave)" },
            { "Gigant_Character_BP_Rockwell", "R-Giganotosaurus" },
            { "Gigant_Character_BP_Corrupt", "Corrupted Giganotosaurus" },
            { "Gigant_Character_BP", "Giganotosaurus" },
            { "GiantTurtle_Character_BP", "Megachelon" },
            { "Ghost_YoungIceFox_DinoCompanion_Character_BP_FE", "Ghost Veilwyn" },
            { "Ghost_YiLing_Character_BP_FE", "Ghost Yi Ling" },
            { "Ghost_Xenomorph_Character_BP_Male_Surface_FE", "Ghost Reaper King (Surface)" },
            { "Ghost_Spino_Character_BP_FE", "Ghost Spinosaurus" },
            { "Ghost_ShoulderDragon_Character_BP_Winter_FE", "Ghost Drakeling (Winter)" },
            { "Ghost_ShoulderDragon_Character_BP_Summer_FE", "Ghost Drakeling (Summer)" },
            { "Ghost_ShoulderDragon_Character_BP_Spring_FE", "Ghost Drakeling (Spring)" },
            { "Ghost_ShoulderDragon_Character_BP_Autumn_FE", "Ghost Drakeling (Autumn)" },
            { "Ghost_Rex_Character_BP_FE", "Ghost Rex" },
            { "Ghost_Owl_Character_BP_FE", "Ghost Snow Owl" },
            { "Ghost_Otter_Character_BP_FE", "Ghost Otter" },
            { "Ghost_Megalodon_Character_BP_FE", "Ghost Megalodon" },
            { "Ghost_Mantis_Character_BP_FE", "Ghost Mantis" },
            { "Ghost_LanternPug_Character_BP_FE", "Ghost Bulbdog" },
            { "Ghost_Gigantoraptor_Character_BP_FE", "Ghost Gigantoraptor" },
            { "Ghost_Direwolf_Character_BP_FE", "Ghost Direwolf" },
            { "Ghost_Deinonychus_Character_BP_FE", "Ghost Deinonychus" },
            { "Ghost_Ceratosaurus_Character_BP_ASA_FE", "Ghost Ceratosaurus" },
            { "Ghost_Cat_Character_BP_FE", "Ghost Cat" },
            { "Ghost_Basilisk_Character_BP_FE", "Ghost Basilisk" },
            { "Ghost_Argent_Character_BP_FE", "Ghost Argentavis" },
            { "Ghost_Ankylo_Character_BP_FE", "Ghost Ankylosaurus" },
            { "Ghost_Angler_Character_BP_FE", "Ghost Anglerfish" },
            { "GasBags_Character_BP_Eden", "R-Gasbags" },
            { "GasBags_Character_BP", "Gasbags" },
            { "Galli_Character_BP", "Gallimimus" },
            { "Gacha_Claus_Character_BP", "Gacha Claus" },
            { "Gacha_Character_BP_Claus", "Gacha Claus" },
            { "Gacha_Character_BP", "Gacha" },
            { "Fractalis_Character_BP", "Fractalis" },
            { "ForestKaiju_Character_BP_Medium", "Forest Titan (Beta)" },
            { "ForestKaiju_Character_BP_Hard", "Forest Titan (Alpha)" },
            { "ForestKaiju_Character_BP_Easy", "Forest Titan (Gamma)" },
            { "ForestKaiju_Character_BP", "Forest Titan" },
            { "FlyingAnt_Character_BP", "Titanomyrma Soldier" },
            { "Fjordhawk_Character_BP", "Fjordhawk" },
            { "FireLion_Character_BP", "Pyromane" },
            { "Fenrir_Character_BP", "Fenrir" },
            { "Fasola_Character_BP_Aberrant", "Aberrant Fasolasuchus" },
            { "Fasola_Character_BP", "Fasolasuchus" },
            { "Exosuit_RTS_Character_BP", "Exo Mek" },
            { "Exosuit_Character_BP", "Exo-Mek" },
            { "Euryp_Character", "Eurypterid" },
            { "Equus_Character_BP_Unicorn", "Unicorn" },
            { "Equus_Character_BP_Eden", "R-Equus" },
            { "Equus_Character_BP_Aberrant", "Aberrant Equus" },
            { "Equus_Character_BP", "Equus" },
            { "Enraged Triceratops", "Alpha Corrupted Triceratops" },
            { "Enforcer_Character_BP", "Enforcer" },
            { "EndTank_Lunar_Character_BP", "X-Defense Unit" },
            { "EndTank_Character_BP", "Defense Unit" },
            { "EndDrone_Lunar_Character_BP", "X-Drone" },
            { "EndDrone_Character_BP_Med", "Attack Drone" },
            { "EndDrone_Character_BP_Hard", "Attack Drone" },
            { "EndDrone_Character_BP_Easy", "Attack Drone" },
            { "EndDrone_Character_BP", "Attack Drone" },
            { "EndBossSpiderL_Character_BP_Medium", "Broodmother (Beta)" },
            { "EndBossSpiderL_Character_BP_Hard", "Broodmother (Alpha)" },
            { "EndBossSpiderL_Character_BP_Easy", "Broodmother (Gamma)" },
            { "EndBossSpiderL_Character_BP", "Broodmother" },
            { "EndBoss_Character", "Overseer" },
            { "EelBoss_Character_BP", "Moeder, Master of the Ocean" },
            { "Eel_Character_BP_Aberrant", "Aberrant Electrophorus" },
            { "Eel_Character_BP", "Electrophorus" },
            { "DwarvenWarrior_Character_BP", "Dwarfen Warrior" },
            { "DwarvenPackLeader_Character_BP", "Dwarven Leader" },
            { "DwarvenGuardian_Character_BP", "Dwarven Guardian" },
            { "DwarvenBerserk_Character_BP", "Dwarven Berserk" },
            { "Dunkle_Character_BP", "Dunkleosteus" },
            { "DungBeetle_Character_BP_Aberrant", "Aberrant Dung Beetle" },
            { "DungBeetle_Character_BP", "Dung Beetle" },
            { "Dreadnoughtus_Character_BP", "Dreadnoughtus" },
            { "Dragonfly_Character_BP_Aberrant", "Aberrant Meganeura" },
            { "Dragonfly_Character_BP", "Meganeura" },
            { "Dragon_Character_BP_Boss_Medium_Ragnarok", "Dragon (Beta)" },
            { "Dragon_Character_BP_Boss_Medium", "Dragon (Beta)" },
            { "Dragon_Character_BP_Boss_Hard_Ragnarok", "Dragon (Alpha)" },
            { "Dragon_Character_BP_Boss_Hard", "Dragon (Alpha)" },
            { "Dragon_Character_BP_Boss_Easy_Ragnarok", "Dragon (Gamma)" },
            { "Dragon_Character_BP_Boss_Easy", "Dragon (Gamma)" },
            { "Dragon_Character_BP_Boss", "Dragon" },
            { "Dolphin_Character_BP", "Ichthyosaurus" },
            { "Doggo_Character_BP", "Armadoggo" },
            { "Doed_Character_BP_Aberrant", "Aberrant Doedicurus" },
            { "Doed_Character_BP", "Doedicurus" },
            { "DodoWyvern_Character_BP_FE", "Dodo Wyvern" },
            { "DodoWyvern_Character_BP", "Dodo Wyvern" },
            { "DodoRex_Character_BP_FE", "Dodo Rex" },
            { "DodoRex_Character_BP", "Dodo Rex" },
            { "Dodo_Character_BP_Mouser", "Dodo Mouser" },
            { "Dodo_Character_BP_Bunny", "Bunny Dodo" },
            { "Dodo_Character_BP_Birthday", "Dodo (Birthday)" },
            { "Dodo_Character_BP_Aberrant", "Aberrant Dodo" },
            { "Dodo_Character_BP", "Dodo" },
            { "Direwolf_LL_Character_BP", "Dire Wolf" },
            { "Direwolf_Character_BP_Eden", "R-Direwolf" },
            { "Direwolf_Character_BP_Corrupted_Zombie", "Direwolf (Revenant)" },
            { "Direwolf_Character_BP", "Direwolf" },
            { "Direbear_LL_Character_BP", "Dire Bear" },
            { "Direbear_Character_Polar", "Polar Bear" },
            { "Direbear_Character_BP_Aberrant", "Aberrant Dire Bear" },
            { "Direbear_Character_BP", "Dire Bear" },
            { "Diplodocus_Character_BP_Aberrant", "Aberrant Diplodocus" },
            { "Diplodocus_Character_BP", "Diplodocus" },
            { "Diplocaulus_Character_BP_Aberrant", "Aberrant Diplocaulus" },
            { "Diplocaulus_Character_BP", "Diplocaulus" },
            { "Dinopithecus_Character_BP", "Dinopithecus" },
            { "Dimorph_Character_BP_Corrupted_Zombie", "Dimorphodon (Revenant)" },
            { "Dimorph_Character_BP_Corrupt", "Corrupted Dimorphodon" },
            { "Dimorph_Character_BP_Aberrant", "Aberrant Dimorphodon" },
            { "Dimorph_Character_BP", "Dimorphodon" },
            { "Dimetro_Character_BP_Aberrant", "Aberrant Dimetrodon" },
            { "Dimetro_Character_BP", "Dimetrodon" },
            { "Dilo_Character_BP_Rockwell", "R-Dilophosaur" },
            { "Dilo_Character_BP_Lightning", "Dilophosaur (Lightning)" },
            { "Dilo_Character_BP_Corrupt_Zombie", "Dilophosaurus (Revenant)" },
            { "Dilo_Character_BP_Corrupt", "Corrupted Dilophosaur" },
            { "Dilo_Character_BP", "Dilophosaur" },
            { "DevilFox_Character_BP_Thrall", "Malwyn (Thrall)" },
            { "DevilFox_Character_BP_Corrupt_Zombie", "Malwyn (Revenant)" },
            { "DevilFox_Character_BP", "Malwyn" },
            { "Desmodus_Character_BP", "Desmodus" },
            { "DesertKaiju_FirstFlockChar_BP", "Desert Titan Flock" },
            { "DesertKaiju_Character_BP_Medium", "Desert Titan (Beta)" },
            { "DesertKaiju_Character_BP_Hard", "Desert Titan (Alpha)" },
            { "DesertKaiju_Character_BP_Easy", "Desert Titan (Gamma)" },
            { "DesertKaiju_Character_BP", "Desert Titan" },
            { "DeinotheriumASA_Character_BP", "Deinotherium" },
            { "Deinosuchusasa_Character_BP", "Deinosuchus" },
            { "DeinosuchusASA_Character_BP", "Deinosuchus" },
            { "Deinonychus_Character_BP", "Deinonychus" },
            { "Defender_Character_BP", "Defense Unit" },
            { "Deathworm_Character_BP", "Deathworm" },
            { "DarkPegasus_Character_BP", "Dreadmare" },
            { "Dakosaurus_Character_BP", "Dakosaurus" },
            { "Daeodon_Character_BP_Eden", "R-Daeodon" },
            { "Daeodon_Character_BP", "Daeodon" },
            { "Cymathoa_Character_BP", "Cymathoa" },
            { "Cyclops_Character_BP", "Cyclop" },
            { "CrystalWyvern_Character_BP_WS", "Wyvern (Tropical)" },
            { "CrystalWyvern_Character_BP_Mega", "Alpha Crystal Wyvern" },
            { "CrystalWyvern_Character_BP_Ember", "Wyvern (Ember)" },
            { "CrystalWyvern_Character_BP_Blood", "Wyvern (Blood)" },
            { "Cryolophosaurus_Character_BP_Thrall", "Cryolophosaurus (Thrall)" },
            { "Cryolophosaurus_Character_BP", "Cryolophosaurus" },
            { "Crab_Character_BP", "Karkinos" },
            { "CorruptTumor_Character_BP", "Corrupt Tumor" },
            { "Compy_Character_BP", "Compy" },
            { "Coel_Character_BP_Ocean", "Coelacanth (Ocean)" },
            { "Coel_Character_BP_Aberrant", "Aberrant Coelacanth" },
            { "Coel_Character_BP", "Coelacanth" },
            { "Cnidaria_Character_BP_Aberrant", "Aberrant Cnidaria" },
            { "Cnidaria_Character_BP", "Cnidaria" },
            { "ChupaCabra_Character_BP_Surface", "Nameless (Surface)" },
            { "ChupaCabra_Character_BP", "Nameless" },
            { "Chrysaora_Character_BP", "Chrysaora" },
            { "Cherufe_Character_BP", "Magmasaur" },
            { "ChalkGolem_Character_BP", "Chalk Golem" },
            { "Chalico_Character_BP_Lightning", "Chalicotherium (Lightning)" },
            { "Chalico_Character_BP_Corrupt", "Corrupted Chalicotherium" },
            { "Chalico_Character_BP", "Chalicotherium" },
            { "Ceratosaurus_Character_BP_Thrall", "Ceratosaurus (Thrall)" },
            { "Ceratosaurus_Character_BP_ASA", "Ceratosaurus" },
            { "CaveWolf_Character_BP", "Ravager" },
            { "CaveTroll_Character_BP", "Cave Troll" },
            { "CaveMinotaur_Character_BP_New", "Minotaur (Cave)" },
            { "Cat_Character_BP", "Cat" },
            { "Carno_Character_BP_Rockwell", "R-Carnotaurus" },
            { "Carno_Character_BP_Lightning", "Carnotaurus (Lightning)" },
            { "Carno_Character_BP_Corrupt", "Corrupted Carnotaurus" },
            { "Carno_Character_BP_Child_Corrupt_Zombie", "Carnotaurus (Revenant)" },
            { "Carno_Character_BP_Aberrant", "Aberrant Carnotaurus" },
            { "Carno_Character_BP", "Carnotaurus" },
            { "Carcha_Character_BP", "Carcharodontosaurus" },
            { "Car_Vehicle_BP", "BattleRig" },
            { "Canoe_BP", "Canoe" },
            { "camelsaurus_Character_BP", "Morellatops" },
            { "BunnyOviraptor_Character_BP", "Bunny Oviraptor" },
            { "BrainSlug_Character_BP", "Noglin" },
            { "Boss_Gorgon_Character_BP_Medium", "Natrix (Beta)" },
            { "Boss_Gorgon_Character_BP_Hard", "Natrix (Alpha)" },
            { "Boss_Gorgon_Character_BP_Easy", "Natrix (Gamma)" },
            { "Boss_Gorgon_Character_BP", "Natrix" },
            { "Boss_Cyclops_Character_BP_Medium", "Thodes (Beta)" },
            { "Boss_Cyclops_Character_BP_Hard", "Thodes (Alpha)" },
            { "Boss_Cyclops_Character_BP_Easy", "Thodes (Gamma)" },
            { "Boss_Cyclops_Character_BP", "Thodes" },
            { "Bone_Trike_Character_BP_FE", "Skeletal Triceratops" },
            { "Bone_Trike_Character_BP", "Skeletal Triceratops" },
            { "Bone_Stego_Character_BP_FE", "Skeletal Stegosaurus" },
            { "Bone_Stego_Character_BP", "Skeletal Stegosaurus" },
            { "Bone_Sauropod_Character_BP_FE", "Skeletal Brontosaurus" },
            { "Bone_Sauropod_Character_BP", "Skeletal Brontosaurus" },
            { "Bone_Quetz_Character_BP_FE", "Skeletal Quetzal" },
            { "Bone_Quetz_Character_BP", "Skeletal Quetzal" },
            { "Bone_MegaWyvern_Character_BP_Fire_FE", "Skeletal Fire Wyvern" },
            { "Bone_MegaWyvern_Character_BP_Fire", "Skeletal Fire Wyvern" },
            { "Bone_MegaRex_Character_BP_FE", "Skeletal Rex" },
            { "Bone_MegaRex_Character_BP", "Skeletal Rex" },
            { "Bone_MegaRaptor_Character_BP_FE", "Skeletal Raptor" },
            { "Bone_MegaRaptor_Character_BP", "Skeletal Raptor" },
            { "Bone_MegaCarno_Character_BP_FE", "Skeletal Carnotaurus" },
            { "Bone_MegaCarno_Character_BP", "Skeletal Carnotaurus" },
            { "Bone_Jerboa_Character_BP_FE", "Skeletal Jerboa" },
            { "Bone_Jerboa_Character_BP", "Skeletal Jerboa" },
            { "Bone_Gigant_Character_BP_FE", "Skeletal Giganotosaurus" },
            { "Bone_Gigant_Character_BP", "Skeletal Gigantosaurus" },
            { "BogSpider_Character_BP", "Bloodstalker" },
            { "Bog_Tapejara_Character_BP", "X-Tapejara" },
            { "Bog_Spino_Character_BP", "X-Spino" },
            { "Bog_Raptor_Character_BP", "X-Raptor" },
            { "Bog_Paracer_Character_BP", "X-Paracer" },
            { "Bog_Para_Character_BP", "X-Parasaur" },
            { "BoaFrill_Character_BP_Aberrant", "Aberrant Titanoboa" },
            { "BoaFrill_Character_BP", "Titanoboa" },
            { "Bison_Character_BP", "Bison" },
            { "BionicTrike_Character_BP", "Tek Triceratops" },
            { "BionicStego_Character_BP", "Tek Stegosaurus" },
            { "BionicRex_Character_BP", "Tek Rex" },
            { "BionicRaptor_Character_BP", "Tek Raptor" },
            { "BionicQuetz_Character_BP", "Tek Quetzal" },
            { "BionicPara_Character_BP", "Tek Parasaur" },
            { "BionicGigant_Character_BP", "Tek Giganotosaurus" },
            { "Bigfoot_Character_BP_Aberrant", "Aberrant Gigantopithecus" },
            { "Bigfoot_Character_BP", "Gigantopithecus" },
            { "Berserk_Raptor_Character_BP", "Raptor (Berserk)" },
            { "Berserk_Otter_Character_BP", "Otter (Berserk)" },
            { "Berserk_Carno_Character_BP", "Carnotaurus (Berserk)" },
            { "Bee_Queen_Character_BP", "Giant Queen Bee" },
            { "Bee_Character_BP", "Giant Bee" },
            { "Beaver_Character_BP", "Castoroides" },
            { "Bat_Character_BP", "Onyc" },
            { "Basilosaurus_Character_BP", "Basilosaurus" },
            { "Basilisk_Character_BP", "Basilisk" },
            { "Baryonyx_Character_BP_Aberrant", "Aberrant Baryonyx" },
            { "Baryonyx_Character_BP", "Baryonyx" },
            { "AstralRex_Character_BP", "Rex (Astral)" },
            { "AstralRaptor_Character_BP", "Raptor (Astral)" },
            { "AstralMegalodon_Character_BP", "Megalodon (Astral)" },
            { "AstralMammoth_Character_BP", "Mammoth (Astral)" },
            { "AstralDirewolf_Character_BP", "Direwolf (Astral)" },
            { "AstralCarno_Character_BP", "Carnotaurus (Astral)" },
            { "AstralArgent_Character_BP", "Argentavis (Astral)" },
            { "Astral_Tusoteuthis_Character_BP", "Tusoteuthis (Astral)" },
            { "Astral_Mosa_Character_BP", "Mosasaurus (Astral)" },
            { "Arthro_Character_BP_Lightning", "Arthropluera (Astral)" },
            { "Arthro_Character_BP_Corrupt", "Corrupted Arthropluera" },
            { "Arthro_Character_BP_Aberrant", "Aberrant Arthropluera" },
            { "Arthro_Character_BP", "Arthropluera" },
            { "Argent_Character_BP", "Argentavis" },
            { "Archelon_Character_BP_ASA", "Archelon" },
            { "Archa_Character_BP", "Archaeopteryx" },
            { "Ant_Character_BP", "Titanomyrma" },
            { "Ankylo_Character_BP_Aberrant", "Aberrant Ankylosaurus" },
            { "Ankylo_Character_BP", "Ankylosaurus" },
            { "Angler_Character_BP_Aberrant", "Aberrant Anglerfish" },
            { "Angler_Character_BP", "Anglerfish" },
            { "AngelFox_Character_BP", "Solwyn" },
            { "Andrewsarchus_Character_BP", "Andrewsarchus" },
            { "Ammonite_Character", "Ammonite" },
            { "Amargasaurus_Character_BP", "Amargasaurus" },
            { "Alpha_Leedsichthys_Character_BP", "Alpha Leedsichthys" },
            { "ALPHA_ChupaCabra_Character_BP", "Alpha Nameless" },
            { "Allo_Character_BP_Rockwell", "R-Allosaurus" },
            { "Allo_Character_BP", "Allosaurus" },
            { "Achatina_Character_BP_Aberrant", "Aberrant Achatina" },
            { "Achatina_Character_BP", "Achatina" }
        };

        public static string? GetNameFromArchetype(string? archetype)
        {
            if (string.IsNullOrWhiteSpace(archetype))
                return null;
            int dotPos = archetype.LastIndexOf(".", StringComparison.InvariantCulture);
            if (dotPos >= 0 && archetype.Length > (dotPos + 1))
                archetype = archetype.Substring(dotPos + 1);
            if (archetype.Length > 2 && archetype.EndsWith("_C", StringComparison.InvariantCultureIgnoreCase))
                archetype = archetype.Substring(0, archetype.Length - 2);
            if (Names.ContainsKey(archetype))
                return Names[archetype];
            Logger.Instance.Log($"Clean dino name not found for [{archetype}].", Logger.LogLevel.WARNING);
            return null;
        }
    }
}
